AppBundle\Entity\Bet:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\BetRepository
    table: bets
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdDatetime:
            type: datetime
            column: created_datetime
        betTime:
            type: datetime
            column: bet_time
        status:
            type: integer
            length: 2
        result:
            type: string
            length: 255
            nullable: true
        homeOdds:
            type: decimal
            scale: 2
        awayOdds:
            type: decimal
            scale: 2
        closedDatetime:
            type: datetime
            column: closed_datetime
            nullable: true
    manyToOne:
        homeTeam:
            targetEntity: AppBundle\Entity\Team
        awayTeam:
            targetEntity: AppBundle\Entity\Team
        game:
            targetEntity: AppBundle\Entity\Game