AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        balance:
            type: decimal
            scale: 2
            nullable: true
